// ---------- Blender-authored kart animation clips ----------
// Generated by tools/export-kart-clips.py (Blender 4.5 headless). Do not hand edit.
// Each clip maps a rig node name to keyframed channels sampled at `fps`; the runtime
// evaluates them in vehicles.js animateKart(). Empty until the pipeline has run.
const KART_CLIPS={version:0,fps:30,clips:{}};
