const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const THREE=require('../vendor/three.min.js'),anime=require('../vendor/anime.umd.min.js');
function fixture(mobile=false){const scene=new THREE.Scene(),context={THREE,anime,scene,matchMedia:q=>({matches:mobile&&q.includes('coarse')}),orientOnTrack:(m,u,lat,h)=>m.position.set(u*100,h,lat),track:{len:100},trackPoint:(u,lat,h,v)=>v.set(u*100,h,lat),du_dist:(u,v)=>(v-u)*100,game:{racers:[]}};vm.createContext(context);for(const file of ['effects.js','addon-effects.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),context);return {scene,context,run:s=>vm.runInContext(s,context)};}
let n=0;function test(name,fn){try{fn();n++;console.log('PASS',name);}catch(e){console.error('FAIL',name);throw e;}}
test('All 24 source abilities have distinct finite world-space geometry',()=>{const {scene,run}=fixture(),ids=run('Object.keys(ADDON_FX_COLORS).slice(0,24)'),signatures=new Set();for(const id of ids){run(`spawnAddonEffect('${id}',.2,1,null,{duration:3});stepAddonEffects(.1)`);const mesh=scene.children.at(-1),names=[];mesh.traverse(o=>{names.push(o.name);for(const v of [...o.position.toArray(),...o.scale.toArray(),...o.quaternion.toArray()])assert.ok(Number.isFinite(v));if(o.geometry){assert.ok(o.geometry.attributes.position.count>0);assert.ok(o.geometry.attributes.position.array.every(Number.isFinite));}});assert.ok(names.filter(Boolean).length>=3,id+' must have layered anatomy');signatures.add(names.join('|'));}assert.equal(ids.length,24);assert.equal(signatures.size,24);assert.equal(scene.children.length,24);run('clearAddonEffects()');});
test('Live projectile entities follow collisions; dead entities remove VFX',()=>{const {scene,run}=fixture();run("const projectile={u:.2,lat:1,life:2};spawnAddonEffect('fire',.2,1,null,{entity:projectile,duration:2,phase:'projectile'});projectile.u=.4;projectile.lat=3;stepAddonEffects(.1)");assert.equal(scene.children[0].position.x,40);assert.equal(scene.children[0].position.z,3);run('projectile.life=0;stepAddonEffects(.1)');assert.equal(scene.children.length,0);});
test('Real anime.js contact envelope advances only with simulation dt and expires',()=>{const {scene,run}=fixture();run("const hit=spawnAddonContact('missile',.2,0,null)");assert.equal(run('hit.timeline.paused'),true);const start=run('hit.envelope.spread');run('stepAddonEffects(.2)');assert.ok(run('hit.envelope.spread')>start);const spread=run('hit.envelope.spread'),life=run('hit.life');run('stepAddonEffects(0)');assert.equal(run('hit.envelope.spread'),spread);assert.equal(run('hit.life'),life);const shards=scene.children[0].getObjectByName('contact-shards');assert.ok(shards.instanceMatrix.array.every(Number.isFinite));run('stepAddonEffects(.5)');assert.equal(scene.children.length,0);});
test('Mobile cap evicts/disposes materials and canceled anime contacts never revive',()=>{const {scene,run}=fixture(true);let disposed=0;const materials=new Set();for(let i=0;i<30;i++){run("spawnAddonContact('pyre',.2,0,null)");scene.traverse(o=>{if(o.material&&!materials.has(o.material)){materials.add(o.material);o.material.addEventListener('dispose',()=>disposed++);}});}assert.equal(scene.children.length,12);assert.ok(disposed>0);run('clearAddonEffects();stepAddonEffects(.3);clearAddonEffects()');assert.equal(scene.children.length,0);assert.equal(disposed,materials.size);});
test('Wave2 zones remain planted; following signatures move with owners',()=>{const {scene,run}=fixture();run("const owner={u:.2,lat:0};spawnPowerEffect('gaia',.1,0,'#fff',owner);spawnPowerEffect('nomad',.1,0,'#fff',owner);spawnPowerEffect('terra',.1,0,'#fff',owner);owner.u=.4;stepPowerEffects(.1)");assert.equal(scene.children[0].position.x,10);assert.equal(scene.children[1].position.x,10);assert.equal(scene.children[2].position.x,40);run('clearPowerEffects()');});
test('Predictive line covers 24m of real track and dynamic geometry is disposed',()=>{const {scene,run}=fixture();run("const owner={u:.2,lat:0};spawnPowerEffect('cognara',.2,0,'#fff',owner);stepPowerEffects(.1)");const line=scene.children[0].getObjectByName('predictive-road-line'),a=line.geometry.attributes.position;assert.ok(Math.abs(a.getX(a.count-1)-a.getX(0)-24)<.01);let disposed=0;line.geometry.addEventListener('dispose',()=>disposed++);run('clearPowerEffects()');assert.equal(disposed,1);});
test('Pyre visible annulus matches its 3.5m safe center and 7m threat radius',()=>{const {scene,run}=fixture();run("spawnAddonEffect('pyre',.2,0,null,{phase:'zone',radius:7,duration:4})");const root=scene.children[0],ring=root.getObjectByName('molten-annulus');assert.equal(ring.geometry.parameters.innerRadius*root.scale.x,3.5);assert.equal(ring.geometry.parameters.outerRadius*root.scale.x,7);assert.equal(root.userData.effectRadius,7);run('clearAddonEffects()');});
test('Summon missiles use blades; travelling earth uses ruptures; bursts are anime contacts',()=>{const {scene,run}=fixture();for(const id of ['growth','cascade','monolith','earth-spire'])run(`spawnAddonEffect('${id}',.2,0,null,{phase:'projectile',radius:2})`);assert.ok(scene.children[0].getObjectByName('growth-lance'));assert.ok(!scene.children[0].getObjectByName('arbor-flower'));assert.ok(scene.children[1].getObjectByName('cascade-flying-blade'));assert.ok(scene.children[2].getObjectByName('travelling-rupture'));assert.ok(!scene.children[3].getObjectByName('earthen-glass-spire'));run("spawnAddonEffect('rend',.2,0,null,{phase:'burst'})");assert.ok(scene.children.at(-1).getObjectByName('contact-shock'));assert.ok(run('addonEffects.at(-1).timeline'));run('clearAddonEffects()');});
test('Consumed Nexus decoys vanish and Gaia root visuals use actual zone pose',()=>{const {scene,run}=fixture();run("const owner={u:.2,lat:0};const abilityZones=[{kind:'decoy',owner,u:.2,lat:0,life:8},{kind:'roots',owner,u:.16,lat:0,life:5}];spawnPowerEffect('nexus',.2,0,'#fff',owner);spawnPowerEffect('gaia',.2,0,'#fff',owner);stepPowerEffects(.1)");assert.equal(scene.children[1].position.x,16);run('abilityZones.shift();stepPowerEffects(.1)');assert.equal(scene.children.length,1);run('clearPowerEffects()');});
test('Live hazards survive mobile/desktop overflow and reject optional contacts',()=>{for(const mobile of [true,false]){const {scene,run}=fixture(mobile);run("const entities=[];for(let i=0;i<72;i++){const e={u:i/100,lat:0,life:4};entities.push(e);spawnAddonEffect('acid',e.u,0,null,{entity:e,duration:.1,phase:'zone'});spawnAddonContact('fire',0,0,null);}");assert.equal(run('addonEffects.filter(f=>f.entity).length'),72);run('stepAddonEffects(.2)');assert.equal(scene.children.length,72);assert.ok(run('addonEffects.every(f=>f.mesh.parent===scene)'));run('entities[0].life=0;stepAddonEffects(.1)');assert.equal(scene.children.length,71);run('clearAddonEffects()');assert.equal(scene.children.length,0);}});
test('Civic ribbon follows eligible beneficiary and hides if all rivals phase',()=>{const {scene,run}=fixture();run("const owner={u:.2,lat:0},phased={u:.21,lat:0,phase:2},eligible={u:.25,lat:1,phase:0};game.racers=[owner,phased,eligible];spawnPowerEffect('civic',.2,0,'#fff',owner);stepPowerEffects(.1)");const line=scene.children[0].getObjectByName('civic-beneficiary'),a=line.geometry.attributes.position;assert.equal(line.visible,true);assert.ok(Math.abs(a.getX(a.count-1)-a.getX(0)-5)<.01);run('eligible.phase=2;stepPowerEffects(.1)');assert.equal(line.visible,false);run('clearPowerEffects()');});
console.log(`${n} addon VFX tests passed`);
