const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const noop=()=>{};
const context={console,Math,Set,Map,Infinity,game:{state:'race',racers:[],trauma:0},TRACK_W:16,track:{len:1000},rng:()=>.5,
 clamp:(v,a,b)=>Math.max(a,Math.min(v,b)),wrap01:x=>((x%1)+1)%1,du_dist:(a,b)=>{let d=b-a;if(d>.5)d--;if(d<-.5)d++;return d*1000;},
 SFX:new Proxy({},{get:()=>noop}),setToast:noop,raceFX:new Proxy({},{get:()=>noop}),missiles:[],scene:{remove:noop},disposeProjectile:noop,
 applyBoost:(r,d,m)=>{r.boost=Math.max(r.boost||0,d);r.boostTarget=m;},trackPoint:noop,_p:{},_v1:{set:noop},goldFx:{emit:noop},hitFx:{emit:noop},hud:{vig:{}},setTimeout:noop,rumble:noop,haptic:noop,
 spawnAddonEffect:(id,u,lat,owner,options)=>context.effects.push({id,u,lat,owner,options}),spawnAddonContact:(id,u,lat)=>context.contacts.push({id,u,lat}),clearAddonEffects:()=>{context.effects=[];context.contacts=[];},effects:[],contacts:[]};
vm.createContext(context);
vm.runInContext(fs.readFileSync(path.join(__dirname,'../abilities.js'),'utf8'),context);
const game=fs.readFileSync(path.join(__dirname,'../game.js'),'utf8');
vm.runInContext(game.slice(game.indexOf('function hitRacer('),game.indexOf('function stepWorld(')),context);
vm.runInContext(fs.readFileSync(path.join(__dirname,'../addons.js'),'utf8'),context);
const run=s=>vm.runInContext(s,context),cases=[];
function test(name,fn){try{fn();console.log('PASS',name);cases.push(true);}catch(e){console.error('FAIL',name,e.stack);cases.push(false);}}
function racer(u,lat=0){return {u,lat,speed:40,tokens:5,spin:0,hitCd:0,phase:0,regen:0,shield:0,reflect:0,slow:0,vault:0,finished:false,isPlayer:false,div:{id:'zenflow',acc:0xffffff},addonAI:Infinity};}
function setup(id,u=.1,targetU=.126,targetLat=0){run('clearAddons()');context.r=racer(u);context.r.isPlayer=true;context.o=racer(targetU,targetLat);context.game.racers=[context.r,context.o];context.game.state='race';run(`initAddons(r,${JSON.stringify(id)});initAddons(o);o.addonAI=Infinity;`);}
function step(seconds){for(let t=0;t<seconds;t+=.02){for(const r of context.game.racers){for(const k of ['spin','hitCd','phase','regen','slow'])r[k]=Math.max(0,(r[k]||0)-.02);}run('stepAddons(.02)');}}
function cast(id,targetU=.126,targetLat=0){setup(id,.1,targetU,targetLat);assert.equal(run('useAddon(r)'),true);}
test('24 unique catalog entries: all live powers, all three boosts and four archived elements',()=>{assert.equal(run('ADDONS.length'),24);assert.equal(run('new Set(ADDONS.map(a=>a.id)).size'),24);assert.ok(run('ADDONS.every(a=>a.cooldown>=18&&a.description.length>30)'));});
test('Selection, race, spin, vault, finish and cooldown guards are authoritative',()=>{setup('invalid');assert.equal(run('useAddon(r)'),false);for(const state of ['menu','countdown','paused','results']){setup('fire');context.game.state=state;assert.equal(run('useAddon(r)'),false);}for(const prop of ['spin','vault','finished','addonCooldown']){setup('fire');context.r[prop]=1;assert.equal(run('useAddon(r)'),false);}setup('fire');assert.equal(run('useAddon(r)'),true);assert.equal(run('useAddon(r)'),false);});
test('Volcanic Ward absorbs one missile and grants an ordinary shield',()=>{cast('ward');assert.equal(context.r.shield,6);context.missiles.push({owner:context.o,u:.095,lat:0});step(.1);assert.equal(context.missiles.length,0);assert.ok(context.contacts.some(e=>e.id==='ward'));});
test('Caustic Bloom slows only rivals in its footprint',()=>{cast('acid',.124);step(.5);assert.ok(context.o.slow>1);assert.equal(context.r.slow,0);context.o.lat=7;context.o.slow=0;step(1);assert.equal(context.o.slow,0);});
test('Growth plants a stationary summon and spends exactly three targeted lances',()=>{cast('growth',.145);step(4);assert.equal(context.effects.filter(e=>e.id==='growth'&&e.options.phase==='projectile').length,3);assert.ok(context.contacts.length>=3);});
test('Cyber Serpent steers into another lane before contact',()=>{cast('cyber',.14,3);step(.65);assert.ok(context.o.spin>0);assert.ok(context.contacts.some(e=>e.id==='cyber'));});
test('Venom Surge pierces three racers and leaves a crystal bed',()=>{cast('venom',.12);const q=racer(.135),s=racer(.15);context.game.racers.push(q,s);step(.48);assert.ok(context.o.slow>0&&q.slow>0&&s.slow>0);assert.ok(run("addonEntities.some(e=>e.id==='venom'&&e.phase==='zone')"));});
test('Monolith rupture detonates into a broad terminal blast',()=>{cast('monolith',.143,4);step(.55);assert.ok(context.o.spin>0);});
test('Sumi Tide slows and pulls laterally toward its center',()=>{cast('ink',.125,3);step(.5);assert.ok(context.o.lat<3&&context.o.slow>0);});
test('Astral collapse is telegraphed, pulls, then detonates',()=>{cast('astral',.13,3);step(.6);assert.equal(context.o.spin,0);assert.ok(context.o.lat<3);step(1.05);assert.ok(context.o.spin>0);});
test('Cascade fires three staggered blades with a final hard hit',()=>{cast('cascade',.145);step(1.2);assert.equal(context.effects.filter(e=>e.id==='cascade'&&e.options.phase==='projectile').length,3);assert.ok(context.o.spin>0);});
test('Celestial Rend only strikes after its 1.1s warning',()=>{cast('rend',.132);step(.8);assert.equal(context.o.spin,0);step(.36);assert.ok(context.o.spin>0);});
test('Pyre Crown keeps its hollow center safe and burns its boundary',()=>{cast('pyre',.125);const q=racer(.131);context.game.racers.push(q);step(.5);assert.equal(context.o.slow,0);assert.ok(q.slow>0);});
test('Kraken slams alternate footprint sides',()=>{cast('kraken',.126,-3);const q=racer(.126,3);context.game.racers.push(q);step(.65);assert.ok(context.o.spin>0);assert.equal(q.spin,0);step(.9);assert.ok(q.spin>0);});
test('Electrical Sphere chains beyond its initial radius through adjacent racers',()=>{cast('electrical',.123);const q=racer(.13),s=racer(.137);context.game.racers.push(q,s);step(.55);assert.ok(context.o.slow>0&&q.slow>0&&s.slow>0);});
test('Live Earthen Spire becomes a terminal blockade, separate from archived Earth',()=>{cast('earth-spire',.137);step(.7);assert.ok(run("addonEntities.some(e=>e.id==='earth-spire'&&e.phase==='zone')"));assert.ok(context.o.spin>0);});
test('Verdant Gate rewards its owner crossing once with shield and surge',()=>{cast('verdant-gate');context.r.u=.112;step(.25);assert.ok(context.r.shield>0&&context.r.boost>0);const contacts=context.contacts.length;step(.5);assert.equal(context.contacts.length,contacts);});
test('Tidewrought Ring cleanses crossing racers and owner gets stronger boost',()=>{cast('tide-ring',.112);context.r.u=.112;context.r.slow=context.o.slow=3;step(.3);assert.equal(context.r.slow,0);assert.equal(context.o.slow,0);assert.ok(context.r.boostTarget>context.o.boostTarget);});
test('Fire Portal phases without teleporting lap position and leaves exit fire',()=>{cast('fire-portal');context.r.u=.112;const distance=context.r.u;step(.3);assert.ok(context.r.phase>0&&context.r.boost>0);assert.equal(context.r.u,distance);assert.ok(run("addonEntities.some(e=>e.id==='fire-boost'&&e.phase==='zone')"));});
test('Electric Boost gives immediate surge plus short range arc',()=>{cast('electric-boost',.109);assert.ok(context.r.boost>0&&context.o.slow>0);});
test('Magic Boost clears slowing and sustains regeneration',()=>{setup('magic-boost');context.r.slow=4;run('useAddon(r)');assert.equal(context.r.slow,0);assert.equal(context.r.regen,4);assert.equal(context.r.boost,4);});
test('Fire Boost lays an actual slowing trail while moving',()=>{cast('fire-boost',.096);step(.3);assert.ok(context.r.boost>0&&context.o.slow>0);assert.ok(run("addonEntities.some(e=>e.id==='fire-boost')"));});
test('Archived Fire explodes on first contact with splash damage',()=>{cast('fire',.12);const q=racer(.121,3.4);context.game.racers.push(q);step(.25);assert.ok(context.o.spin>0&&q.spin>0);});
test('Archived Water pierces and pushes rivals sideways',()=>{cast('water',.12,1);const q=racer(.135,1);context.game.racers.push(q);step(.5);assert.ok(context.o.lat>1&&q.lat>1&&q.slow>0);});
test('Archived Earth lays four crust sections behind the racer',()=>{cast('earth',.087,1);step(.5);assert.equal(context.effects.filter(e=>e.id==='earth').length,4);assert.ok(context.o.slow>0&&context.o.lat>1);});
test('Archived Wind combines owner tailwind and rival vortex shove',()=>{cast('wind',.12,1);step(.4);assert.ok(context.r.boost>0&&context.o.slow>0&&context.o.lat>2);});
test('A fast projectile sweeps through a racer across the lap seam',()=>{setup('cyber',.995,.004);run('useAddon(r);stepAddons(.2)');assert.ok(context.o.spin>0);});
test('Phase Walk does not consume projectiles or piercing charges',()=>{cast('fire',.113);context.o.phase=5;const q=racer(.13);context.game.racers.push(q);run('stepAddons(.3)');assert.equal(context.o.spin,0);assert.ok(q.spin>0);cast('venom',.113);context.o.phase=5;run('stepAddons(.15)');assert.equal(run('addonEntities[0].pierce'),3);assert.equal(run('addonEntities[0].contacts.size'),0);});
test('Phase and shields block harmful gameplay and contact animations',()=>{for(const guard of ['phase','shield']){cast('water',.12,1);context.o[guard]=5;step(.3);assert.equal(context.o.slow,0);assert.equal(context.o.lat,1);assert.equal(context.contacts.length,0);}cast('fire',.12);context.o.reflect=4;step(.3);assert.ok(context.r.spin>0);assert.equal(context.o.spin,0);});
test('Pause freezes cooldowns and entities; race clear retires references',()=>{cast('fire');const life=run('addonEntities[0].life'),cd=context.r.addonCooldown;context.game.state='paused';run('stepAddons(2)');assert.equal(context.r.addonCooldown,cd);assert.equal(run('addonEntities[0].life'),life);const entity=context.effects[0].options.entity;run('clearAddons()');assert.equal(entity.life,0);assert.equal(run('addonEntities.length'),0);});
test('Finished owners retire persistent hazards and entities have a hard ceiling',()=>{cast('acid');context.r.finished=true;step(.1);assert.equal(run('addonEntities.length'),0);setup('acid');run("for(let i=0;i<100;i++)addonZone('acid',r,24,5)");assert.equal(run('addonEntities.length'),72);step(6);assert.equal(run('addonEntities.length'),0);});
if(cases.some(x=>!x))process.exitCode=1;else console.log(`${cases.length} add-on gameplay tests passed`);
