/* These assertions run inside the real game-regression VM, using actual physics,
   world collision/pickup, AI, and signed lap bookkeeping functions. */
module.exports=({test,assert,run,racer,opponent,context})=>{
 const reset=id=>{racer(id);run('mines.length=0;itemBoxes.length=0;r.u=.2;r.distance=.2;r.lat=0;game.laps=3;game.raceTime=10;');};
 const pickup=()=>run('tokens.push({u:r.u,lat:r.lat,t:0,mesh:{visible:true,rotateY(){}}})');
 test('Time field consumes one shield without slowing that tick, then refreshes through the common slow gate',()=>{reset('zenflow');opponent();run('o.shield=4;useSpecial(r);stepAbilities(.01)');assert.equal(run('o.shield'),0);assert.equal(run('o.slow'),0);run('stepAbilities(.01)');assert.equal(run('o.slow'),.6);reset('zenflow');opponent();run('useSpecial(r);stepAbilities(.01)');assert.equal(run('o.slow'),1.2);run('o.u=wrap01(r.u+.05);stepAbilities(.5)');assert.ok(run('o.slow')<1);});
 test('Fortune steals from nearest three, consumes ordinary shield, and cannot pierce a vault',()=>{reset('collective');run("for(const d of [.03,.025,.02,.01]){const q=new Racer(ROSTER[0],false,1);q.u=r.u+d;q.tokens=3;q.specialAI=Infinity;game.racers.push(q)};useSpecial(r)");assert.equal(run('game.racers[1].tokens'),3);assert.equal(run('game.racers.slice(2).every(q=>q.tokens===2)'),true);reset('collective');opponent();run('o.tokens=3;o.shield=4;useSpecial(r)');assert.equal(run('o.tokens'),3);assert.equal(run('o.shield'),0);run('r.specialCooldown=0;o.vault=4;useSpecial(r)');assert.equal(run('o.tokens'),3);});
 test('Phase prevents both token and item-box pickup and leaves missiles and mines alive',()=>{reset('hybrid');pickup();run('itemBoxes.push({u:r.u,lat:r.lat,t:0,mesh:{visible:true,rotateY(){}},star:{rotation:{x:0,y:0}},core:{rotation:{x:0}}});useSpecial(r);stepWorld(.01)');assert.equal(run('r.tokens+r.roulette'),0);assert.equal(run('tokens[0].mesh.visible&&itemBoxes[0].mesh.visible'),true);run('itemBoxes.length=0;tokens.length=0;mines.push({u:r.u,lat:r.lat,life:5,owner:{},mesh:{}});missiles.push({u:r.u,lat:r.lat,life:5,speed:0,owner:{},mesh:{rotateZ(){}}});stepWorld(.01)');assert.equal(run('mines.length+missiles.length'),2);assert.equal(run('r.spin'),0);});
 test('Decoy ignores its own missile and all mines, then consumes exactly one hostile missile',()=>{reset('nexus');run('useSpecial(r);missiles.push({owner:r,u:r.u,lat:r.lat,mesh:{}});mines.push({owner:{},u:r.u,lat:r.lat,mesh:{}});stepAbilities(.01)');assert.equal(run('missiles.length+mines.length'),2);assert.equal(run('abilityZones.length'),1);run('missiles.push({owner:{},u:r.u,lat:r.lat,mesh:{}});stepAbilities(.01)');assert.equal(run('missiles.length'),1);assert.equal(run('abilityZones.length'),0);});
 test('Mutual ram commits both hits while a phased contact is ignored',()=>{reset('kinetic');opponent('kinetic',.001);run('useSpecial(r);useSpecial(o);stepWorld(.01)');assert.ok(run('r.spin>0&&o.spin>0'));reset('kinetic');opponent('hybrid',.001);run('useSpecial(r);useSpecial(o);stepWorld(.01)');assert.equal(run('r.spin+o.spin'),0);});
 test('Mirror does not block slows or token theft and reflected hits cannot bounce',()=>{reset('juris');opponent('juris');run('useSpecial(r);useSpecial(o);powerSlow(r,.8,o)');assert.equal(run('r.slow'),.8);assert.equal(run('r.reflect'),4);run("hitRacer(r,'test',o)");assert.equal(run('r.reflect'),0);assert.equal(run('o.reflect'),4);assert.equal(run('r.spin'),0);assert.ok(run('o.spin')>0);});
 test('Sonic miss remains committed and Vector chooses a clear four metre landing',()=>{reset('signal');run('useSpecial(r)');assert.equal(run('r.specialCooldown'),16);reset('vector');opponent('zenflow',.001);run('o.lat=4;useSpecial(r)');assert.equal(run('r.lat'),-4);assert.equal(run('r.distance'),.2);assert.equal(run('r.specialActive'),.5);});
 test('Loom refresh is exactly 0.8 seconds and finished targets are unaffected',()=>{reset('loom');opponent('zenflow',-.005);run('useSpecial(r);stepAbilities(.01)');assert.equal(run('o.slow'),.8);run('o.finished=true;o.slow=0;stepAbilities(.01)');assert.equal(run('o.slow'),0);run('stepAbilities(5)');assert.equal(run('abilityZones.length'),0);});
 test('Magnet cannot collect during spin, phase, or vault',()=>{for(const state of ['spin','phase','vault']){reset('aether');pickup();run(`useSpecial(r);r.${state}=2;stepAbilities(.01)`);assert.equal(run('r.tokens'),0,state);}reset('aether');pickup();run('useSpecial(r);stepAbilities(.01)');assert.equal(run('r.tokens'),1);});
 test('Drone has a six metre lane gate and exactly three deterministic pulses',()=>{reset('animus');opponent();run('o.lat=6;useSpecial(r);stepAbilities(.01)');assert.equal(run('o.slow'),0);reset('animus');opponent();run('o.reflect=4;useSpecial(r);stepAbilities(.01)');assert.equal(run('o.reflect'),3.99);assert.ok(run('o.slow')>0);assert.equal(run('r.specialPulses'),1);run('stepAbilities(1.49)');assert.equal(run('r.specialPulses'),2);run('stepAbilities(.01)');assert.equal(run('r.specialPulses'),2);run('stepAbilities(2.5)');assert.equal(run('r.specialPulses'),3);assert.ok(Math.abs(run('o.speed')-40*.84**3)<1e-8);});
 test('Vault freezes item use and touching tokens but leaves owner and distant economy free',()=>{reset('ledger');opponent('zenflow',.01);run('o.tokens=3;o.item="burst";o.shield=4;o.reflect=4;useSpecial(r);stepAbilities(.01)');assert.ok(run('o.vault')>0);assert.equal(run('o.shield'),4);assert.ok(run('o.reflect')>0);assert.equal(run('useItem(o)'),false);run('tokens.push({u:o.u,lat:o.lat,t:0,mesh:{visible:true,rotateY(){}}});stepWorld(.01)');assert.equal(run('o.tokens'),3);assert.equal(run('r.vault'),0);reset('ledger');opponent('zenflow',.04);run('useSpecial(r);stepAbilities(.01)');assert.equal(run('o.vault'),0);});
 test('Anchor prevents heavy contact displacement and speed slams but remains hittable',()=>{reset('terra');opponent('zenflow',.001);run('r.speed=30;o.weight=100;useSpecial(r);for(let i=0;i<24;i++){o.lat=r.lat;o.u=r.u+.001;stepWorld(1/120)}');assert.ok(Math.abs(run('r.lat'))<=.05);assert.equal(run('r.speed'),30);run("hitRacer(r,'ram',o)");assert.ok(run('r.spin')>0);run('stepAbilities(3.5)');assert.equal(run('r.anchor'),0);});
 test('Perimeter shoves and slows without spinning, preserves shield for first hit, and ignores phase',()=>{reset('obsidian');opponent('zenflow',.001);run('useSpecial(r);powerSlow(r,.8,o);stepWorld(.01)');assert.equal(run('r.shield'),4);assert.ok(run('o.lat')>=1.2);assert.ok(run('o.slow')>0);assert.equal(run('o.spin'),0);run("hitRacer(r,'test',o)");assert.equal(run('r.shield'),0);assert.equal(run('r.spin'),0);assert.equal(run('r.perimeter'),4);reset('obsidian');opponent('hybrid',.001);run('useSpecial(r);useSpecial(o);stepWorld(.01)');assert.equal(run('o.lat'),0);assert.equal(run('o.slow'),0);});
 test('Shared Lane grants nearest unfinished racer a real speed benefit without self-boosting',()=>{const sample=active=>{reset('civic');opponent('zenflow',-.01);run(`r.speed=30;o.speed=30;o.throttle=true;${active?'useSpecial(r);':''}for(let i=0;i<60;i++){o.u=wrap01(r.u-.01);stepAbilities(1/120);stepRacer(o,1/120)}`);return run('o.speed');};const control=sample(false),draft=sample(true);assert.ok(draft>control,`${draft} > ${control}`);assert.equal(run('r.civicDraft'),0);reset('civic');opponent('zenflow',.001);run('o.finished=true;useSpecial(r);stepAbilities(.01)');assert.equal(run('o.civicDraft'),0);});
 test('Predictive Line tightens fixed steering and expires without harming anyone',()=>{const sample=active=>{reset('cognara');run(`r.speed=30;r.throttle=true;r.ai.steer=.6;${active?'useSpecial(r);':''}for(let i=0;i<30;i++)stepRacer(r,1/120)`);return run('r.lat');};assert.ok(sample(true)>sample(false));reset('cognara');opponent();run('useSpecial(r);stepAbilities(4)');assert.equal(run('r.predict'),0);assert.equal(run('o.spin'),0);});
 test('Root Net slows crossing rivals and its active grip reduces a real wall speed loss',()=>{reset('gaia');opponent('zenflow',-.004);run('useSpecial(r);stepAbilities(.01)');assert.equal(run('o.slow'),.8);run('stepAbilities(5)');assert.equal(run('abilityZones.length'),0);const sample=active=>{reset('gaia');run(`r.speed=40;r.lat=TRACK_W/2;r.theta=.6;${active?'useSpecial(r);':''}stepRacer(r,1/120)`);return run('r.speed');};assert.ok(sample(true)>sample(false));});
 test('Waypoint Hop advances six metres and shares lap, finish, and reverse-exploit bookkeeping',()=>{reset('nomad');run('r.lat=2;useSpecial(r)');assert.ok(Math.abs(run('r.distance')-.206)<1e-9);assert.ok(Math.abs(run('r.u')-.206)<1e-9);assert.equal(run('r.lat'),2);assert.equal(run('r.specialCooldown'),13);assert.equal(run('r.phase'),.6);reset('nomad');run('r.distance=.997;r.u=.997;useSpecial(r)');assert.equal(run('r.lap'),2);assert.equal(run('r.lapTimes.length'),1);assert.ok(run('r.u')<.01);reset('nomad');run('r.distance=2.997;r.u=.997;r.lap=3;r.highestLap=3;useSpecial(r)');assert.equal(run('r.finished'),true);assert.equal(run('r.finishTime'),10);reset('nomad');run('r.distance=-.003;r.u=.997;useSpecial(r)');assert.equal(run('r.lap'),1);assert.equal(run('r.lapTimes.length'),0);});
 test('Second Wind fires through spin, cleanses and surges without recovering tokens',()=>{reset('eon');run('r.spin=1;r.slow=2;r.wheelspin=1;r.tokens=4;r.lastLostTokens=3;useSpecial(r)');assert.equal(run('r.spin+r.slow+r.wheelspin'),0);assert.equal(run('r.tokens'),4);assert.equal(run('r.lastLostTokens'),3);assert.equal(run('r.regen'),5);assert.equal(run('r.hitCd'),1);assert.ok(run('r.boost>0&&r.surge>0'));run('r.hitCd=0');assert.equal(run('powerSlow(r,2,null)'),false);run("hitRacer(r,'test')");assert.ok(run('r.spin')>0);});
 test('New power AI evaluates actual nearby threats and economy',()=>{for(const id of ['ledger','terra','obsidian','civic','cognara','gaia','nomad']){reset(id);assert.equal(run('aiWantsSpecial(r)'),false,id+' idle');opponent('zenflow',id==='gaia'?-.008:id==='nomad'?.008:.001);run('o.tokens=3');assert.equal(run('aiWantsSpecial(r)'),true,id+' opportunity');}reset('eon');assert.equal(run('aiWantsSpecial(r)'),true);run('r.speed=r.maxSpeed');assert.equal(run('aiWantsSpecial(r)'),false);});
 test('A slow is a felt handicap: lower ceiling, blunted throttle and a damped boost',()=>{
  const drive=setup=>{reset('zenflow');run(`r.throttle=true;r.speed=20;${setup};for(let i=0;i<120;i++)stepRacer(r,1/120)`);return run('r.speed');};
  const clear=drive(''),snared=drive('r.slow=3');
  assert.ok(snared<clear*.8,`a snared racer loses real speed: ${snared} vs ${clear}`);
  // A racer already at pace is dragged down instead of merely capped.
  reset('zenflow');run('r.throttle=false;r.speed=40;r.slow=3;for(let i=0;i<30;i++)stepRacer(r,1/120)');
  assert.ok(run('r.speed')<34,'carried speed bleeds toward the cap while coasting');
  // Boosting out of a snare is damped, and every cleansing power clears the slow
  // before it boosts, so its own surge arrives at full strength.
  reset('zenflow');run('applyBoost(r,2,1.4,1)');const full=run('r.boostTarget'),fullSurge=run('r.surge');
  reset('zenflow');run('r.slow=3;applyBoost(r,2,1.4,1)');
  assert.ok(run('r.boostTarget')<full&&run('r.boostTarget')>1,'a damped boost still helps');
  assert.ok(run('r.surge')<fullSurge);
  reset('zenflow');run('r.slow=3;r.regen=2;applyBoost(r,2,1.4,1)');assert.equal(run('r.boostTarget'),full,'slow resistance restores the full boost');
  reset('eon');run('r.slow=4;useSpecial(r)');assert.equal(run('r.boostTarget'),1.18,'Second Wind cleanses before it surges');
 });
 test('A committed cast is never inert: an unanswered lance and an empty siphon vent into thrust',()=>{
  reset('signal');run('useSpecial(r)');
  assert.equal(run('r.specialCooldown'),16,'the miss stays committed');assert.ok(run('r.boost')>0&&run('r.surge')>0,'and is spent as thrust');
  reset('signal');opponent('zenflow',.002);run('useSpecial(r)');
  assert.equal(run('r.boost'),0,'a lance that connects is not also a boost');assert.ok(run('o.spin')>0);
  reset('collective');run('useSpecial(r)');assert.ok(run('r.boost')>0,'no reserves within reach vents the siphon');
  reset('collective');opponent('zenflow',.002);run('o.tokens=3;useSpecial(r)');
  assert.equal(run('r.tokens'),1);assert.equal(run('r.boost'),0,'a siphon that takes a token does not also boost');
 });
 test('All duration and cooldown timers freeze outside live simulation and reset on initialization',()=>{reset('terra');run('useSpecial(r);r.vault=3;r.perimeter=3;r.civicDraft=3;r.predict=3');for(const state of ['paused','roster','countdown','results']){run(`game.state='${state}';stepAbilities(2)`);assert.equal(run('r.specialCooldown'),19);assert.equal(run('r.anchor'),3.5);assert.equal(run('r.vault+r.perimeter+r.civicDraft+r.predict'),12);}run('initAbility(r)');assert.equal(run('r.vault+r.anchor+r.perimeter+r.civicDraft+r.predict+r.specialCooldown'),0);});
};
