"""Blender-authored looping hinge motion and tessellated fabric, exported to Three.js."""
import bpy, math, json, os
root=os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
bpy.ops.object.select_all(action='SELECT');bpy.ops.object.delete(use_global=False)
scene=bpy.context.scene;scene.render.fps=30;scene.frame_start=1;scene.frame_end=121
pivot=bpy.data.objects.new('Lantern suspension hinge',None);scene.collection.objects.link(pivot)
for frame,angle in [(1,0),(16,.065),(31,.09),(46,.04),(61,0),(76,-.065),(91,-.09),(106,-.04),(121,0)]:
    pivot.rotation_euler.z=angle;pivot.keyframe_insert(data_path='rotation_euler',frame=frame)
# Explicitly sample Blender's interpolated curve; runtime never approximates the authored keys.
samples=[]
for frame in range(1,122):
    scene.frame_set(frame);samples.append(round(pivot.rotation_euler.z,6))
verts=[];faces=[];uvs=[]
for j in range(5):
    for i in range(13):
        u=i/12;v=j/4;verts.append((u*2.8,0,-v*(1.15-.45*u)));uvs.extend([u,v])
for j in range(4):
    for i in range(12):
        a=j*13+i;faces.extend([a,a+1,a+14,a,a+14,a+13])
mesh=bpy.data.meshes.new('Woven pennant');mesh.from_pydata(verts,[],[faces[i:i+3] for i in range(0,len(faces),3)]);mesh.update()
flag=bpy.data.objects.new('Pennant fixed mast seam',mesh);scene.collection.objects.link(flag)
mat=bpy.data.materials.new('Woven fabric');mat.use_nodes=True;bs=mat.node_tree.nodes.get('Principled BSDF');bs.inputs['Roughness'].default_value=.92;bs.inputs['Base Color'].default_value=(.16,.5,.48,1);mesh.materials.append(mat)
# Export Blender Z-up -> game Y-up.
data={'version':1,'source':'Blender '+bpy.app.version_string,'duration':4,'hinge':samples,'fabric':{'positions':[n for x,y,z in verts for n in (x,z,-y)],'indices':faces,'uv':uvs}}
with open(os.path.join(root,'world-motion-data.js'),'w') as f:f.write('/* Generated by tools/author-world-motion.py; do not hand-edit. */\nconst WORLD_MOTION_DATA='+json.dumps(data,separators=(',',':'))+';\n')
bpy.ops.wm.save_as_mainfile(filepath=os.path.join(root,'.tools/living-world.blend'))
print('Exported Blender hinge clip and 96-triangle fabric to world-motion-data.js')
